name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: heet09
  PRODUCER_IMAGE_NAME: producer
  CONSUMER_IMAGE_NAME: consumer
  API_IMAGE_NAME: api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push producer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./producer.Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.PRODUCER_IMAGE_NAME }}:v1

      - name: Build and push consumer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./consumer.Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.CONSUMER_IMAGE_NAME }}:v2

      - name: Build and push api image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./api.Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.API_IMAGE_NAME }}:v1
